/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp com.juknousi.meegopas.xml -a meegopasadaptor -c MeegopasAdaptor -l Route -i route.h
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "../include/meegopasadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class MeegopasAdaptor
 */

MeegopasAdaptor::MeegopasAdaptor(Route *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

MeegopasAdaptor::~MeegopasAdaptor()
{
    // destructor
}

void MeegopasAdaptor::route(const QString &name, const QString &coord)
{
    // handle method call com.juknousi.meegopas.route
    parent()->route(name, coord);
}

